[workspace]
members = [
    "crystal-node",
    "core/json-rpc",
    "core/auth",
    "core/chain",
    "libs/message",
    "libs/result",
    "libs/evm",
    "libs/storage",
    "libs/hashing",
    "libs/evm-nogas"
]